### PR TITLE
Update Sample using Redisson and JCache

### PR DESCRIPTION
**Pull request by backwind1233**
## Purpose
The old sample use Redisson client directly, since the Redisson is an implementation of JCache API (JSR-107), update the sample to show how to use JCache and Redisson.

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Comment by backwind1233** [comment]
Link https://github.com/MicrosoftDocs/azure-docs-pr/pull/260292

**Comment by philon-msft** [comment]
Thanks for your contribution, @backwind1233. Your code using Redisson+JCache would make a good new sample, but we probably want to keep this one using Redisson directly as-is. People use Redis/Redisson for other scenarios aide from caching, so we need to provide general samples not tied to caching.

**Comment by backwind1233** [comment]
Thank you for your feedback and for considering my contribution. I understand the importance of providing general samples that cover various scenarios with Redis/Redisson beyond caching. @philon-msft

**Comment by philon-msft** [comment]
I still think your sample code is very valuable - would you be willing to update this PR so it adds a new sample project called "java-redisson-jcache", as a sibling to the "java-redisson" directory?

**Review by edburns — APPROVED** [review]

**Comment by edburns** [comment]
Also make sure to add a git lightweight tag and direct the reader to check it out from the guide.

**Comment by edburns** [comment]
Hello @backwind1233 , I want to make the requested changes, but I am not a contributor to your fork of `azure-cache-redis-samples`. Can you please invite me so I can push commits to your fork?

```
edburns@Edwards-MBP azure-cache-redis-samples % git push backwind1233
git push backwind1233
ERROR: Permission to backwind1233/azure-cache-redis-samples.git denied to edburns.
fatal: Could not read from remote repository.
```

Thanks,

Ed

**Comment by backwind1233** [comment]
Close this pr, redirect to https://github.com/Azure-Samples/azure-cache-redis-samples/pull/44.

**Pull request closed without merging**
