### PR TITLE
adding .NET web app sample

### PR DESCRIPTION
**Pull request by CawaMS**
## Purpose

* ...

## Pull Request Type
What kind of change does this Pull Request introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Documentation content changes
[ ] Other... Please describe:
```

### CODE REVIEW

**Review by MSFTeegarden — APPROVED** [review]
I recommend adding an entry for this demo on the top-level readme in the repo. Also a good idea to run this by Philo :)

**Comment by MSFTeegarden** [comment]
#sign-off

**Comment by philon-msft** [comment]
Should go under a folder named "AspNetCore" rather than ".NET"

**Comment by philon-msft** [comment]
Should also include a README.md describing the project and how to deploy/run it

**Pull request closed without merging**
